#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0") && pwd)

usage="$(basename "$0") [-h, --help] [--serial_port] [--binary_file] [--save_test_output] -- Run tests on real hardware

Optional arguments:
    -h, --help          Show this help message and exit
    --serial_port       Serial port to which Arduino Nano is connected to, default is /dev/ttyUSB0
    --binary_file       Path to the binary 'main', default is '${SCRIPT_DIR}/main'
    --save_test_output  Save the output files generated by this script, default is false"

SERIAL_PORT="/dev/ttyUSB0"
BINARY_FILE="${SCRIPT_DIR}/main"
SAVE_TEST_OUTPUT="false"

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            echo "${usage}"
            exit 0
            ;;
        --serial_port)
            SERIAL_PORT="$2"
            shift
            shift
            ;;
        --binary_file)
            BINARY_FILE="$2"
            shift
            shift
            ;;
        --save_test_output)
            SAVE_TEST_OUTPUT="true"
            shift
            ;;
        *)
            echo "Unknown argument $1"
            exit 1
            ;;
    esac
done

if [[ ! -e "${BINARY_FILE}" ]]; then
    echo "Executable ${BINARY_FILE} was not found"
    exit 1
fi

sudo ${BINARY_FILE} ${SERIAL_PORT} testing
python3 ${SCRIPT_DIR}/test_data/verify_real_hw_result.py ${SCRIPT_DIR}/test_data

if [[ "${SAVE_TEST_OUTPUT}" == "false" ]]; then
    rm -f ${SCRIPT_DIR}/test_data/real_hw_tb_result.txt
fi
