#!/bin/bash

usage="$(basename "$0") [-h] [--save_test_output] -- Run tests on real hardware

Positional arguments:
    serial_port         Serial port to which Arduino Nano is connected to, e.g. /dev/ttyUSB0
Optional arguments:
    -h                  Show this help message and exit
    --binary_file       Path to the binary main, default is <current_dir>/main
    --save_test_output  Save the output files generated by this script, set to false by default"

if [[ "$1" == "-h" ]]; then
    echo "${usage}"
    exit 0
fi

SERIAL_PORT="$1"
SAVE_TEST_OUTPUT="false"
BINARY_FILE="`dirname "$0"`/main"

shift
while [[ $# -gt 0 ]]; do
    case $1 in
        -h)
            echo "${usage}"
            exit 0
            ;;
        --binary_file)
            BINARY_FILE="$2"
            shift
            shift
            ;;
        --save_test_output)
            SAVE_TEST_OUTPUT="true"
            shift
            ;;
        *)
            echo "Unknown argument $1"
            exit 1
            ;;
    esac
done

if [[ ! -e "${BINARY_FILE}" ]]; then
    echo "Executable 'main' was not found"
    echo "${usage}"
    exit 1
fi

sudo ${BINARY_FILE} ${SERIAL_PORT} testing
python3 `dirname "$0"`/test_data/verify_real_hw_result.py `dirname "$0"`/test_data
if [[ "${SAVE_TEST_OUTPUT}" == "false" ]]; then
    rm -f `dirname "$0"`/test_data/real_hw_tb_result.txt
fi
